# -*- mode: ruby -*-
# vi: set ft=ruby :

# Dev VM for C and CPP development on linux
Vagrant.configure("2") do |config|
  config.vm.define "cpp-vm" do |cppvm|
    cppvm.vm.box = "ubuntu/bionic64" # trouble with installing criterion-dev on focal64
    cppvm.vm.box_check_update = true
    cppvm.vm.network "public_network", type: "dhcp"
    cppvm.vm.synced_folder "./data", "/vagrant_data"
    cppvm.vm.provider "virtualbox" do |vb|
      vb.name = "cpp-dev-vm"
      # vb.gui = true
      vb.memory = "2048"
      vb.cpus = 2
    end
    cppvm.vm.provision "shell", inline: <<-SHELL
      apt-add-repository ppa:snaipewastaken/ppa
      apt-get update
      apt-get upgrade -y
      apt-get install -y build-essential gdb cmake zip unzip criterion-dev
    SHELL
  end  
end
